name: terminal
version: 0.1.3
authors:
- Mike Lewis <mike@updroid.com>
description: A terminal emulator written in Dart. Connect its I/O to a WebSocket or whatever you like.
homepage: https://www.github.com/updroidinc/terminal
environment:
  sdk: ^1.10.1
dependencies:
  browser: ^0.10.0
  quiver: ^0.21.3
  http_server: ^0.9.5
  path: ^1.3.9
