name: terminal
version: 0.1.3
authors:
- Mike Lewis <mike@updroid.com>
description: A terminal emulator written in Dart. Connect its I/O to a WebSocket or whatever you like.
homepage: https://www.github.com/updroidinc/terminal
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  quiver: ">=2.1.2 <3.0.0"
  http_server: ">=0.9.8 <1.0.0"
  path: ">=1.6.4 <2.0.0"
dev_dependencies:
  build_runner: ">=1.6.2 <2.0.0"
  build_web_compilers: ">=1.2.0 <3.0.0"
  pedantic: ^1.0.0